trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.8'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Instalar dependências'

  - script: |
      source venv/bin/activate
      pytest
    displayName: 'Executar Testes'

  - script: |
      source venv/bin/activate
      bandit -r app -f json -o bandit-report.json
    displayName: 'Executar SAST (Bandit)'

  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'sonarqube-service-connection'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'flask-app'
      cliProjectName: 'Flask App'
      cliSources: 'app'
      extraProperties: |
        sonar.tests=tests

  - task: SonarQubeAnalyze@5

  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'
